# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_pvalues <- function(data, beta, theta, mu, tau, v, lambda) {
    .Call(`_DISAA_compute_pvalues`, data, beta, theta, mu, tau, v, lambda)
}

update_eta <- function(data, X, beta, theta, tau, v, eta, eta_bound) {
    .Call(`_DISAA_update_eta`, data, X, beta, theta, tau, v, eta, eta_bound)
}

update_parameters <- function(data, X, eta, beta, theta, pi, tau, v, lambda, beta_bound, theta_bound) {
    .Call(`_DISAA_update_parameters`, data, X, eta, beta, theta, pi, tau, v, lambda, beta_bound, theta_bound)
}

