# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_pvalues <- function(data, beta, theta, mu, tau, v, lambda) {
    .Call(`_DISAA_compute_pvalues`, data, beta, theta, mu, tau, v, lambda)
}

precompute_mu_tau <- function(data, X, beta, eta, theta) {
    .Call(`_DISAA_precompute_mu_tau`, data, X, beta, eta, theta)
}

compute_likelihood <- function(eta_i, X_i, beta, tau_i, v_i, data_i, theta) {
    .Call(`_DISAA_compute_likelihood`, eta_i, X_i, beta, tau_i, v_i, data_i, theta)
}

update_parameters <- function(data, X, eta, beta, theta, pi, tau, v, lambda, beta_bound, theta_bound) {
    .Call(`_DISAA_update_parameters`, data, X, eta, beta, theta, pi, tau, v, lambda, beta_bound, theta_bound)
}

