# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

e_step_cpp <- function(params) {
    .Call('_DISAA_e_step_cpp', PACKAGE = 'DISAA', params)
}

m_step_cpp <- function(params) {
    .Call('_DISAA_m_step_cpp', PACKAGE = 'DISAA', params)
}

compute_pvalues_cpp <- function(params) {
    .Call('_DISAA_compute_pvalues_cpp', PACKAGE = 'DISAA', params)
}

update_eta_cpp <- function(params) {
    .Call('_DISAA_update_eta_cpp', PACKAGE = 'DISAA', params)
}

